"""Generates the on-chip self-test ROM for the DE1-SoC bring-up harness.

Writes selftest_rom.svh next to this script: a short stimulus sequence and
the exact output the reference model produces from it. DE1_SoC.sv plays the
stimulus into rx_top and compares the result on hardware, with no host
tooling or analog signal path involved. The sequence is kept short because
the ROM costs 2 * N_STIM * data_bits + 2 * N_OUT * out_bits bits of M10K.

Usage:
    python de1soc/gen_selftest_rom.py
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REFERENCE_DIR = os.path.join(_HERE, "..", "cordic", "reference")
if _REFERENCE_DIR not in sys.path:
    sys.path.insert(0, _REFERENCE_DIR)

import ddc_reference as G

N_STIM = 512


def _sv_array(name, values, bits):
    """Render an int sequence as a SystemVerilog localparam array.

    Args:
        name: Array name.
        values: Integer values.
        bits: Word width; values are emitted as signed decimals.

    Returns:
        The localparam declaration as a string.
    """
    entries = ", ".join(str(int(v)) for v in values)
    return (
        f"localparam logic signed [{bits}-1:0] {name} [0:{len(values)}-1] = '{{\n"
        f"    {entries}\n}};\n"
    )


def render_selftest_svh(cfg, stim_i, stim_q, out_i, out_q) -> str:
    """Render the self-test ROM include file.

    Args:
        cfg: The DDC configuration the vectors were produced under.
        stim_i, stim_q: Input stimulus at cfg.data_bits.
        out_i, out_q: Expected decimated output at cfg.out_bits.

    Returns:
        The contents of selftest_rom.svh as a string.
    """
    return f"""// Generated by de1soc/gen_selftest_rom.py -- do not edit by hand.
// Regenerate:  python de1soc/gen_selftest_rom.py
`ifndef SELFTEST_ROM_SVH
`define SELFTEST_ROM_SVH

// Stimulus and the reference model's exact response to it, for the on-board
// self test in DE1_SoC.sv. Produced at the default DDCConfig:
//   fs_in {cfg.fs_in:.0f} Hz, f_lo {cfg.f_lo_actual:.3f} Hz, decim {cfg.decim},
//   cutoff {cfg.fir_cutoff:.0f} Hz, data_bits {cfg.data_bits}, out_bits {cfg.out_bits}
// Regenerate whenever any of those change, or the board checks against a
// stale configuration and reports a false failure.

`define SELFTEST_N_STIM {len(stim_i)}
`define SELFTEST_N_OUT {len(out_i)}
`define SELFTEST_DATA_BITS {cfg.data_bits}
`define SELFTEST_OUT_BITS {cfg.out_bits}

// Phase increment for the configured LO, the value the board must drive into
// rx_top for the expected outputs below to be the right ones.
`define SELFTEST_PHASE_INC {cfg.phase_bits}'h{cfg.phase_inc:0{(cfg.phase_bits + 3) // 4}x}

{_sv_array("SELFTEST_STIM_I", stim_i, "`SELFTEST_DATA_BITS")}
{_sv_array("SELFTEST_STIM_Q", stim_q, "`SELFTEST_DATA_BITS")}
{_sv_array("SELFTEST_OUT_I", out_i, "`SELFTEST_OUT_BITS")}
{_sv_array("SELFTEST_OUT_Q", out_q, "`SELFTEST_OUT_BITS")}
`endif
"""


def main(argv=None):
    """Regenerate selftest_rom.svh from the reference model's default config.

    Args:
        argv: Unused; present for CLI-tool symmetry with the other generators.

    Returns:
        Process exit code.
    """
    cfg = G.DDCConfig()
    ddc = G.DDC(cfg)
    xi, xq = G.two_tone(N_STIM, cfg)
    r = ddc.run(xi, xq)

    path = os.path.join(_HERE, "selftest_rom.svh")
    with open(path, "w", newline="\n") as f:
        f.write(render_selftest_svh(cfg, r["stim_i"], r["stim_q"], r["out_i"], r["out_q"]))
    print(f"wrote {path}")
    print(f"  {len(r['stim_i'])} stimulus samples -> {len(r['out_i'])} outputs")
    print(f"  ROM: {2 * len(r['stim_i']) * cfg.data_bits + 2 * len(r['out_i']) * cfg.out_bits} bits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
