"""Generates the DE1-SoC bring-up vectors.

selftest_rom.svh is synthesized into DE1_SoC.sv: a stimulus sequence and the
output the reference model produces from it, so a programmed board checks
itself with no host or analog path. adc_vectors.svh is testbench-only: a tone
quantized to LTC2308 codes and the matching outputs, for tb_de1soc_live.

Usage:
    python de1soc/gen_selftest_rom.py
"""

import os
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_REFERENCE_DIR = os.path.join(_HERE, "..", "cordic", "reference")
if _REFERENCE_DIR not in sys.path:
    sys.path.insert(0, _REFERENCE_DIR)

import ddc_reference as G

N_STIM = 512

# Fills one 64-sample UART frame and starts the next, so the live testbench
# sees the frame counter increment.
N_ADC = 640

# 85 kHz against the 80 kHz LO lands at 5 kHz, inside the 20 kHz passband.
ADC_TONE_HZ = 85_000.0
ADC_AMP_DBFS = -6.0

# 12-bit unipolar over 0-4.096 V: code 2048 is mid-scale.
ADC_BITS = 12
ADC_MID = 1 << (ADC_BITS - 1)
ADC_MAX = (1 << ADC_BITS) - 1


def _sv_array(name, values, bits):
    """Render an int sequence as a SystemVerilog localparam array.

    Args:
        name: Array name.
        values: Integer values.
        bits: Word width; values are emitted as signed decimals.

    Returns:
        The localparam declaration as a string.
    """
    entries = ", ".join(str(int(v)) for v in values)
    return (
        f"localparam logic signed [{bits}-1:0] {name} [0:{len(values)}-1] = '{{\n"
        f"    {entries}\n}};\n"
    )


def _sv_array_unsigned(name, values, bits):
    """Render an int sequence as an unsigned SystemVerilog localparam array.

    Args:
        name: Array name.
        values: Non-negative integer values.
        bits: Word width.

    Returns:
        The localparam declaration as a string.
    """
    entries = ", ".join(f"{bits}'d{int(v)}" for v in values)
    return (
        f"localparam logic [{bits}-1:0] {name} [0:{len(values)}-1] = '{{\n"
        f"    {entries}\n}};\n"
    )


def adc_tone_codes(cfg, n, f_hz, amp_dbfs):
    """Quantize a real sinusoid to LTC2308 output codes.

    Straight-binary codes centred on ADC_MID, clipped to the converter's
    range.

    Args:
        cfg: The DDC configuration, for its input sample rate.
        n: Number of conversions.
        f_hz: Tone frequency in Hz.
        amp_dbfs: Tone amplitude relative to the converter's half-scale.

    Returns:
        An int64 array of codes in [0, ADC_MAX].
    """
    amp = (10.0 ** (amp_dbfs / 20.0)) * (ADC_MID - 1)
    t = np.arange(n, dtype=np.float64)
    x = ADC_MID + amp * np.cos(2.0 * np.pi * f_hz * t / cfg.fs_in)
    return np.clip(np.round(x), 0, ADC_MAX).astype(np.int64)


def adc_codes_to_samples(codes, data_bits):
    """Map straight-binary converter codes to the datapath's signed word.

    Mirrors DE1_SoC.sv: subtract mid-scale, then left-justify into the
    datapath word.

    Args:
        codes: Converter codes in [0, ADC_MAX].
        data_bits: Datapath word width.

    Returns:
        An int64 array of signed samples at `data_bits`.
    """
    return (codes - ADC_MID) << (data_bits - ADC_BITS)


def render_adc_vectors_svh(cfg, codes, out_i, out_q) -> str:
    """Render the live-ADC vector include used by tb_de1soc_live.

    Args:
        cfg: The DDC configuration the vectors were produced under.
        codes: LTC2308 codes the model feeds to the controller.
        out_i, out_q: Expected decimated output at cfg.out_bits.

    Returns:
        The contents of adc_vectors.svh as a string.
    """
    return f"""// Generated by de1soc/gen_selftest_rom.py -- do not edit by hand.
// Regenerate:  python de1soc/gen_selftest_rom.py
`ifndef ADC_VECTORS_SVH
`define ADC_VECTORS_SVH

// Testbench-only, not synthesized: a {ADC_TONE_HZ:.0f} Hz tone at {ADC_AMP_DBFS:.0f} dBFS
// quantized to LTC2308 codes, and the decimated output the reference model
// produces from them. The input is real (single-ended CH0), so Q is zero.
//   fs_in {cfg.fs_in:.0f} Hz, f_lo {cfg.f_lo_actual:.3f} Hz, decim {cfg.decim}

`define ADC_N_CODES {len(codes)}
`define ADC_N_OUT {len(out_i)}

{_sv_array_unsigned("ADC_CODES", codes, ADC_BITS)}
{_sv_array("ADC_OUT_I", out_i, "`SELFTEST_OUT_BITS")}
{_sv_array("ADC_OUT_Q", out_q, "`SELFTEST_OUT_BITS")}
`endif
"""


def render_selftest_svh(cfg, stim_i, stim_q, out_i, out_q) -> str:
    """Render the self-test ROM include file.

    Args:
        cfg: The DDC configuration the vectors were produced under.
        stim_i, stim_q: Input stimulus at cfg.data_bits.
        out_i, out_q: Expected decimated output at cfg.out_bits.

    Returns:
        The contents of selftest_rom.svh as a string.
    """
    return f"""// Generated by de1soc/gen_selftest_rom.py -- do not edit by hand.
// Regenerate:  python de1soc/gen_selftest_rom.py
`ifndef SELFTEST_ROM_SVH
`define SELFTEST_ROM_SVH

// Stimulus and the reference model's exact response to it, for the on-board
// self test in DE1_SoC.sv. Produced at the default DDCConfig:
//   fs_in {cfg.fs_in:.0f} Hz, f_lo {cfg.f_lo_actual:.3f} Hz, decim {cfg.decim},
//   cutoff {cfg.fir_cutoff:.0f} Hz, data_bits {cfg.data_bits}, out_bits {cfg.out_bits}
// Regenerate whenever any of those change, or the board checks against a
// stale configuration and reports a false failure.

`define SELFTEST_N_STIM {len(stim_i)}
`define SELFTEST_N_OUT {len(out_i)}
`define SELFTEST_DATA_BITS {cfg.data_bits}
`define SELFTEST_OUT_BITS {cfg.out_bits}

// Phase increment for the configured LO, the value the board must drive into
// rx_top for the expected outputs below to be the right ones.
`define SELFTEST_PHASE_INC {cfg.phase_bits}'h{cfg.phase_inc:0{(cfg.phase_bits + 3) // 4}x}

{_sv_array("SELFTEST_STIM_I", stim_i, "`SELFTEST_DATA_BITS")}
{_sv_array("SELFTEST_STIM_Q", stim_q, "`SELFTEST_DATA_BITS")}
{_sv_array("SELFTEST_OUT_I", out_i, "`SELFTEST_OUT_BITS")}
{_sv_array("SELFTEST_OUT_Q", out_q, "`SELFTEST_OUT_BITS")}
`endif
"""


def main(argv=None):
    """Regenerate selftest_rom.svh from the reference model's default config.

    Args:
        argv: Unused; present for CLI-tool symmetry with the other generators.

    Returns:
        Process exit code.
    """
    cfg = G.DDCConfig()
    ddc = G.DDC(cfg)
    xi, xq = G.two_tone(N_STIM, cfg)
    r = ddc.run(xi, xq)

    path = os.path.join(_HERE, "selftest_rom.svh")
    with open(path, "w", newline="\n") as f:
        f.write(render_selftest_svh(cfg, r["stim_i"], r["stim_q"], r["out_i"], r["out_q"]))
    print(f"wrote {path}")
    print(f"  {len(r['stim_i'])} stimulus samples -> {len(r['out_i'])} outputs")
    print(f"  ROM: {2 * len(r['stim_i']) * cfg.data_bits + 2 * len(r['out_i']) * cfg.out_bits} bits")

    # Live-ADC vectors: single-ended, so Q is zero.
    codes = adc_tone_codes(cfg, N_ADC, ADC_TONE_HZ, ADC_AMP_DBFS)
    adc_xi = adc_codes_to_samples(codes, cfg.data_bits)
    ra = ddc.run(adc_xi, None)

    path = os.path.join(_HERE, "adc_vectors.svh")
    with open(path, "w", newline="\n") as f:
        f.write(render_adc_vectors_svh(cfg, codes, ra["out_i"], ra["out_q"]))
    print(f"wrote {path}")
    print(f"  {len(codes)} ADC codes -> {len(ra['out_i'])} outputs "
          f"({ADC_TONE_HZ:.0f} Hz at {ADC_AMP_DBFS:.0f} dBFS, testbench only)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
