// Generated by rx/gen_fir_coef.py -- do not edit by hand.
// Regenerate:  python rx/gen_fir_coef.py
`ifndef FIR_INTERP_COEF_TABLE_SVH
`define FIR_INTERP_COEF_TABLE_SVH

`define FIR_INTERP_N_TAPS 63
`define FIR_INTERP_L 8
`define FIR_INTERP_COEF_BITS 16
// Longest phase, in taps -- sizes the delay line and the per-phase step
// counter. n_taps is not a multiple of interp in general, so phases are not
// all this long; FIR_INTERP_PHASE_LEN below carries the real per-phase count.
`define FIR_INTERP_MAX_PHASE_LEN 8

// Flat, unfolded: phase p reads FIR_INTERP_COEF[p], [p+L], [p+2L], ...,
// directly against the un-stuffed input history -- see polyphase_decompose()
// in ddc_reference.py for why this needs no fold-pairing offset.
localparam logic signed [`FIR_INTERP_COEF_BITS-1:0] FIR_INTERP_COEF [0:`FIR_INTERP_N_TAPS-1] = '{
    0, 2, 6, 13, 21, 25, 20, 0, -41, -108, -205, -331, -479, -633, -772, -865, -875, -760, -480, 0, 706, 1647, 2814, 4176, 5681, 7256, 8815, 10265, 11512, 12471, 13075, 13276, 13075, 12471, 11512, 10265, 8815, 7256, 5681, 4176, 2814, 1647, 706, 0, -480, -760, -875, -865, -772, -633, -479, -331, -205, -108, -41, 0, 20, 25, 21, 13, 6, 2, 0
};

// Tap count for phase p = ceil((N_TAPS-p)/L). Read from this table rather
// than assumed equal, since N_TAPS need not be a multiple of L.
localparam int FIR_INTERP_PHASE_LEN [0:`FIR_INTERP_L-1] = '{8, 8, 8, 8, 8, 8, 8, 7};

`endif
