// Generated by rx/gen_fir_coef.py -- do not edit by hand.
// Regenerate:  python rx/gen_fir_coef.py
`ifndef FIR_COEF_TABLE_SVH
`define FIR_COEF_TABLE_SVH

`define FIR_N_TAPS 63
// ceil(N_TAPS/2): the unique taps under h[k] == h[N_TAPS-1-k] symmetry,
// including the lone centre tap at index HALF_TAPS-1.
`define FIR_HALF_TAPS 32
`define FIR_COEF_BITS 16

// FIR_COEF[k] pairs with input offsets k and (N_TAPS-1-k) for
// k < HALF_TAPS-1; FIR_COEF[HALF_TAPS-1] is the centre tap, used once, not
// doubled, since offset (N_TAPS-1-k) then equals k itself.
localparam logic signed [`FIR_COEF_BITS-1:0] FIR_COEF [0:`FIR_HALF_TAPS-1] = '{
    0, 0, 0, 1, 3, 6, 9, 13, 16, 16, 11, 0, -19, -46, -81, -119, -154, -180, -187, -165, -105, 0, 154, 354, 594, 862, 1140, 1408, 1645, 1831, 1950, 1984
};

`endif
