// Generated by rx/gen_fir_coef.py -- do not edit by hand.
// Regenerate:  python rx/gen_fir_coef.py
`ifndef FIR_COEF_TABLE_SVH
`define FIR_COEF_TABLE_SVH

`define FIR_N_TAPS 63
// ceil(N_TAPS/2): the unique taps under h[k] == h[N_TAPS-1-k] symmetry,
// including the lone centre tap at index HALF_TAPS-1.
`define FIR_HALF_TAPS 32
`define FIR_COEF_BITS 16

// FIR_COEF[k] pairs with input offsets k and (N_TAPS-1-k) for
// k < HALF_TAPS-1; FIR_COEF[HALF_TAPS-1] is the centre tap, used once, not
// doubled, since offset (N_TAPS-1-k) then equals k itself.
localparam logic signed [`FIR_COEF_BITS-1:0] FIR_COEF [0:`FIR_HALF_TAPS-1] = '{
    0, 0, 1, 2, 3, 3, 2, 0, -5, -14, -26, -41, -60, -79, -97, -108, -109, -95, -60, 0, 88, 206, 352, 522, 710, 907, 1102, 1283, 1439, 1559, 1634, 1660
};

`endif
