// Generated by rx/gen_fir_coef.py -- do not edit by hand.
// Regenerate:  python rx/gen_fir_coef.py
`ifndef FIR_INTERP_COEF_TABLE_SVH
`define FIR_INTERP_COEF_TABLE_SVH

`define FIR_INTERP_N_TAPS 63
`define FIR_INTERP_L 8
`define FIR_INTERP_COEF_BITS 16
// Longest phase, in taps -- sizes the delay line and the per-phase step
// counter. n_taps is not a multiple of interp in general, so phases are not
// all this long; FIR_INTERP_PHASE_LEN below carries the real per-phase count.
`define FIR_INTERP_MAX_PHASE_LEN 8

// Flat, unfolded: phase p reads FIR_INTERP_COEF[p], [p+L], [p+2L], ...,
// directly against the un-stuffed input history -- see polyphase_decompose()
// in ddc_reference.py for why this needs no fold-pairing offset.
localparam logic signed [`FIR_INTERP_COEF_BITS-1:0] FIR_INTERP_COEF [0:`FIR_INTERP_N_TAPS-1] = '{
    0, 0, 2, 9, 24, 47, 76, 106, 127, 127, 90, 0, -153, -372, -646, -949, -1236, -1444, -1499, -1323, -842, 0, 1229, 2832, 4753, 6894, 9118, 11263, 13158, 14646, 15596, 15922, 15596, 14646, 13158, 11263, 9118, 6894, 4753, 2832, 1229, 0, -842, -1323, -1499, -1444, -1236, -949, -646, -372, -153, 0, 90, 127, 127, 106, 76, 47, 24, 9, 2, 0, 0
};

// Tap count for phase p = ceil((N_TAPS-p)/L). Read from this table rather
// than assumed equal, since N_TAPS need not be a multiple of L.
localparam int FIR_INTERP_PHASE_LEN [0:`FIR_INTERP_L-1] = '{8, 8, 8, 8, 8, 8, 8, 7};

`endif
