"""Generates the folded FIR coefficient table from the reference model.

Writes fir_coef_table.svh next to this script, so the RTL's coefficient ROM
is always the same numbers ddc_reference.py computed -- never hand-copied.

The RTL folds the filter around its symmetric taps (h[k] == h[N-1-k]), so it
only needs the first half of the array: h[0..HALF_TAPS-1], where HALF_TAPS =
ceil(N_TAPS/2) and the last entry is the centre tap, used unpaired. That
folding is only valid because fir_taps_quantized() already rejects any
quantization that breaks exact symmetry -- see ddc_reference.py.

Usage:
    python rx/gen_fir_coef.py
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REFERENCE_DIR = os.path.join(_HERE, "..", "cordic", "reference")
if _REFERENCE_DIR not in sys.path:
    sys.path.insert(0, _REFERENCE_DIR)

import ddc_reference as G


def render_fir_coef_svh(coef, coef_bits: int) -> str:
    """Render the folded coefficient table as a SystemVerilog include file.

    Args:
        coef: The full N_TAPS quantized, symmetric filter taps.
        coef_bits: Coefficient word width.

    Returns:
        The contents of fir_coef_table.svh as a string.

    Raises:
        ValueError: If the tap count is even (the folded architecture pairs
            tap k with tap N-1-k and needs a lone centre tap) or the taps
            are not exactly symmetric (the fold would then be computing the
            wrong filter).
    """
    import numpy as np

    n_taps = len(coef)
    if n_taps % 2 == 0:
        raise ValueError(
            f"n_taps={n_taps} is even; the folded architecture needs an odd "
            f"tap count so there is a single unpaired centre tap"
        )
    if not np.array_equal(coef, coef[::-1]):
        raise ValueError(
            "quantized taps are not exactly symmetric -- folding would "
            "compute a different filter than the one that was designed"
        )

    half_taps = (n_taps + 1) // 2
    half = coef[:half_taps]
    entries = ", ".join(str(int(v)) for v in half)
    return f"""// Generated by rx/gen_fir_coef.py -- do not edit by hand.
// Regenerate:  python rx/gen_fir_coef.py
`ifndef FIR_COEF_TABLE_SVH
`define FIR_COEF_TABLE_SVH

`define FIR_N_TAPS {n_taps}
// ceil(N_TAPS/2): the unique taps under h[k] == h[N_TAPS-1-k] symmetry,
// including the lone centre tap at index HALF_TAPS-1.
`define FIR_HALF_TAPS {half_taps}
`define FIR_COEF_BITS {coef_bits}

// FIR_COEF[k] pairs with input offsets k and (N_TAPS-1-k) for
// k < HALF_TAPS-1; FIR_COEF[HALF_TAPS-1] is the centre tap, used once, not
// doubled, since offset (N_TAPS-1-k) then equals k itself.
localparam logic signed [`FIR_COEF_BITS-1:0] FIR_COEF [0:`FIR_HALF_TAPS-1] = '{{
    {entries}
}};

`endif
"""


def main(argv=None):
    """Regenerate fir_coef_table.svh from the reference model's default config.

    Args:
        argv: Unused; present for CLI-tool symmetry with gen_cordic_vectors.py.

    Returns:
        Process exit code.
    """
    cfg = G.DDCConfig()
    ddc = G.DDC(cfg)

    svh_path = os.path.join(_HERE, "fir_coef_table.svh")
    with open(svh_path, "w", newline="\n") as f:
        f.write(render_fir_coef_svh(ddc.coef, cfg.coef_bits))
    print(f"wrote {svh_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
