"""Generates the FIR coefficient tables from the reference model.

Writes fir_coef_table.svh (the folded RX decimator table) and
fir_interp_coef_table.svh (the flat, polyphase-addressed TX interpolator
table) next to this script, so the RTL's coefficient ROMs always match
ddc_reference.py's computed values.

Usage:
    python rx/gen_fir_coef.py
"""

import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REFERENCE_DIR = os.path.join(_HERE, "..", "cordic", "reference")
if _REFERENCE_DIR not in sys.path:
    sys.path.insert(0, _REFERENCE_DIR)

import ddc_reference as G


def render_fir_coef_svh(coef, coef_bits: int) -> str:
    """Render the folded coefficient table as a SystemVerilog include file.

    Args:
        coef: The full N_TAPS quantized, symmetric filter taps.
        coef_bits: Coefficient word width.

    Returns:
        The contents of fir_coef_table.svh as a string.

    Raises:
        ValueError: If the tap count is even (the folded architecture pairs
            tap k with tap N-1-k and needs a lone centre tap) or the taps
            are not exactly symmetric (the fold would then be computing the
            wrong filter).
    """
    import numpy as np

    n_taps = len(coef)
    if n_taps % 2 == 0:
        raise ValueError(
            f"n_taps={n_taps} is even; the folded architecture needs an odd "
            f"tap count so there is a single unpaired centre tap"
        )
    if not np.array_equal(coef, coef[::-1]):
        raise ValueError(
            "quantized taps are not exactly symmetric -- folding would "
            "compute a different filter than the one that was designed"
        )

    half_taps = (n_taps + 1) // 2
    half = coef[:half_taps]
    entries = ", ".join(str(int(v)) for v in half)
    return f"""// Generated by rx/gen_fir_coef.py -- do not edit by hand.
// Regenerate:  python rx/gen_fir_coef.py
`ifndef FIR_COEF_TABLE_SVH
`define FIR_COEF_TABLE_SVH

`define FIR_N_TAPS {n_taps}
// ceil(N_TAPS/2): the unique taps under h[k] == h[N_TAPS-1-k] symmetry,
// including the lone centre tap at index HALF_TAPS-1.
`define FIR_HALF_TAPS {half_taps}
`define FIR_COEF_BITS {coef_bits}

// FIR_COEF[k] pairs with input offsets k and (N_TAPS-1-k) for
// k < HALF_TAPS-1; FIR_COEF[HALF_TAPS-1] is the centre tap, used once, not
// doubled, since offset (N_TAPS-1-k) then equals k itself.
localparam logic signed [`FIR_COEF_BITS-1:0] FIR_COEF [0:`FIR_HALF_TAPS-1] = '{{
    {entries}
}};

`endif
"""


def render_fir_interp_coef_svh(coef_interp, coef_bits: int, interp: int) -> str:
    """Render the interpolator's flat coefficient table and phase metadata.

    Unlike the decimator, this table is not folded: every tap is stored, at
    coef_interp[p + k*interp] for phase p (see ddc_reference.py's
    polyphase_decompose()).

    Args:
        coef_interp: The full N_TAPS quantized interpolator taps (DC gain
            decim/k_gain, not the decimator's 1/k_gain -- see
            fir_taps_quantized's target_dc).
        coef_bits: Coefficient word width.
        interp: Interpolation factor.

    Returns:
        The contents of fir_interp_coef_table.svh as a string.
    """
    n_taps = len(coef_interp)
    phases = G.polyphase_decompose(coef_interp, interp)
    phase_lens = [len(idxs) for idxs in phases]
    entries = ", ".join(str(int(v)) for v in coef_interp)
    lens = ", ".join(str(n) for n in phase_lens)
    return f"""// Generated by rx/gen_fir_coef.py -- do not edit by hand.
// Regenerate:  python rx/gen_fir_coef.py
`ifndef FIR_INTERP_COEF_TABLE_SVH
`define FIR_INTERP_COEF_TABLE_SVH

`define FIR_INTERP_N_TAPS {n_taps}
`define FIR_INTERP_L {interp}
`define FIR_INTERP_COEF_BITS {coef_bits}
// Longest phase, in taps -- sizes the delay line and the per-phase step
// counter. n_taps is not a multiple of interp in general, so phases are not
// all this long; FIR_INTERP_PHASE_LEN below carries the real per-phase count.
`define FIR_INTERP_MAX_PHASE_LEN {max(phase_lens)}

// Flat, unfolded: phase p reads FIR_INTERP_COEF[p], [p+L], [p+2L], ...,
// directly against the un-stuffed input history -- see polyphase_decompose()
// in ddc_reference.py for why this needs no fold-pairing offset.
localparam logic signed [`FIR_INTERP_COEF_BITS-1:0] FIR_INTERP_COEF [0:`FIR_INTERP_N_TAPS-1] = '{{
    {entries}
}};

// Tap count for phase p = ceil((N_TAPS-p)/L). Read from this table rather
// than assumed equal, since N_TAPS need not be a multiple of L.
localparam int FIR_INTERP_PHASE_LEN [0:`FIR_INTERP_L-1] = '{{{lens}}};

`endif
"""


def main(argv=None):
    """Regenerate the FIR coefficient tables from the reference model's default config.

    Args:
        argv: Unused; present for CLI-tool symmetry with gen_cordic_vectors.py.

    Returns:
        Process exit code.
    """
    cfg = G.DDCConfig()
    ddc = G.DDC(cfg)

    decim_path = os.path.join(_HERE, "fir_coef_table.svh")
    with open(decim_path, "w", newline="\n") as f:
        f.write(render_fir_coef_svh(ddc.coef, cfg.coef_bits))
    print(f"wrote {decim_path}")

    interp_path = os.path.join(_HERE, "fir_interp_coef_table.svh")
    with open(interp_path, "w", newline="\n") as f:
        f.write(render_fir_interp_coef_svh(ddc.coef_interp, cfg.coef_bits, cfg.decim))
    print(f"wrote {interp_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
