// Self-checking testbench for ddc_frontend (the fused NCO+mixer datapath,
// before decimation).
//
// Drives every stimulus sample in build/ddc_vectors (generated by
// `python cordic/reference/ddc_reference.py --mix-arch fused --emit-vectors
// build/ddc_vectors`) through the DUT one at a time, using phase0=0 to match
// the reference model's default, and compares mix_i/mix_q against the
// reference's own fused-mixer output. Run via rx/run_sim_ddc.sh, which
// regenerates the vectors first so the RTL and the checked values can never
// drift apart.
//
// Parameters come from the generated ddc_params.svh rather than being
// hand-copied, so a config change in the reference model cannot silently
// desync from the RTL under test.

`timescale 1ns/1ps
`include "ddc_params.svh"

module tb_ddc_frontend #(
    parameter string VEC_DIR = "build/ddc_vectors"
);

    logic clk = 0;
    logic rst_n;

    logic [PHASE_BITS-1:0]        phase_inc;
    logic                         in_valid;
    logic signed [DATA_BITS-1:0]  xi, xq;
    logic                         busy, out_valid;
    logic signed [MIX_BITS-1:0]   mix_i, mix_q;

    ddc_frontend #(
        .PHASE_BITS       (PHASE_BITS),
        .PHASE_TRUNC_BITS (PHASE_TRUNC_BITS),
        .ANG_BITS         (ANG_BITS),
        .DATA_BITS        (DATA_BITS),
        .CORDIC_BITS      (CORDIC_BITS),
        .MIX_BITS         (MIX_BITS)
    ) dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .phase_inc (phase_inc),
        .in_valid  (in_valid),
        .xi        (xi),
        .xq        (xq),
        .busy      (busy),
        .out_valid (out_valid),
        .mix_i     (mix_i),
        .mix_q     (mix_q)
    );

    always #5 clk <= ~clk;

    logic signed [DATA_BITS-1:0] stim_i [0:N_STIM-1];
    logic signed [DATA_BITS-1:0] stim_q [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  mix_i_exp [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  mix_q_exp [0:N_STIM-1];

    int n_fail = 0;

    initial begin
        $readmemh({VEC_DIR, "/stim_i.hex"}, stim_i);
        $readmemh({VEC_DIR, "/stim_q.hex"}, stim_q);
        $readmemh({VEC_DIR, "/mix_i.hex"},  mix_i_exp);
        $readmemh({VEC_DIR, "/mix_q.hex"},  mix_q_exp);

        phase_inc = PHASE_INC;
        rst_n = 0;
        in_valid = 0;
        repeat (2) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        for (int i = 0; i < N_STIM; i++) begin
            xi = stim_i[i];
            xq = stim_q[i];
            in_valid = 1;
            @(posedge clk);   // DUT is idle, so this edge always accepts
            in_valid = 0;
            while (!out_valid) @(posedge clk);

            if (mix_i !== mix_i_exp[i] || mix_q !== mix_q_exp[i]) begin
                n_fail++;
                $display("FAIL sample %0d: xi=%0d xq=%0d", i, stim_i[i], stim_q[i]);
                $display("  expected mix_i=%0d mix_q=%0d", mix_i_exp[i], mix_q_exp[i]);
                $display("  got      mix_i=%0d mix_q=%0d", mix_i, mix_q);
            end
            @(posedge clk);
        end

        if (n_fail == 0)
            $display("ALL %0d SAMPLES PASSED", N_STIM);
        else
            $display("%0d of %0d SAMPLES FAILED", n_fail, N_STIM);

        $finish;
    end

endmodule
