// Self-checking testbench for ddc_frontend (the fused NCO+mixer datapath,
// before any filtering), in both mixing directions.
//
// Drives every stimulus sample in build/ddc_vectors (generated by
// `python cordic/reference/ddc_reference.py --mix-arch fused --emit-vectors
// build/ddc_vectors`) through the DUT one at a time, using phase0=0 to match
// the reference model's default, and compares mix_i/mix_q against the
// reference's own fused-mixer output. Run via rx/run_sim_ddc.sh, which
// regenerates the vectors first so the RTL and the checked values can never
// drift apart.
//
// Three passes, because `downconvert` is a port and not a parameter -- the
// die does both directions, so both have to be exercised on one build:
//
//   1. down        every sample down-converted    -> mix_i/mix_q
//   2. up          every sample up-converted      -> mix_up_i/mix_up_q
//   3. alternating direction toggled every sample -> whichever matches
//
// Pass 3 is the one that earns its keep. Passes 1 and 2 would both succeed
// if the direction were latched once and never updated, or if it leaked from
// the previous sample; only toggling it per sample shows the operand is
// captured per rotation. The reference arrays are directly comparable there
// because both were generated over the same stimulus from phase0=0, and the
// accumulator advances once per accepted sample regardless of direction --
// so sample i sits at phase i*PHASE_INC in every pass.
//
// Parameters come from the generated ddc_params.svh rather than being
// hand-copied, so a config change in the reference model cannot silently
// desync from the RTL under test.

`timescale 1ns/1ps
`include "ddc_params.svh"

module tb_ddc_frontend #(
    parameter string VEC_DIR = "build/ddc_vectors"
);

    logic clk = 0;
    logic rst_n;

    logic [PHASE_BITS-1:0]        phase_inc;
    logic                         downconvert;
    logic                         in_valid;
    logic signed [DATA_BITS-1:0]  xi, xq;
    logic                         busy, out_valid;
    logic signed [MIX_BITS-1:0]   mix_i, mix_q;

    ddc_frontend #(
        .PHASE_BITS       (PHASE_BITS),
        .PHASE_TRUNC_BITS (PHASE_TRUNC_BITS),
        .ANG_BITS         (ANG_BITS),
        .DATA_BITS        (DATA_BITS),
        .CORDIC_BITS      (CORDIC_BITS),
        .MIX_BITS         (MIX_BITS)
    ) dut (
        .clk         (clk),
        .rst_n       (rst_n),
        .phase_inc   (phase_inc),
        .downconvert (downconvert),
        .in_valid    (in_valid),
        .xi          (xi),
        .xq          (xq),
        .busy        (busy),
        .out_valid   (out_valid),
        .mix_i       (mix_i),
        .mix_q       (mix_q)
    );

    always #5 clk <= ~clk;

    logic signed [DATA_BITS-1:0] stim_i [0:N_STIM-1];
    logic signed [DATA_BITS-1:0] stim_q [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  mix_i_exp [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  mix_q_exp [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  up_i_exp  [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  up_q_exp  [0:N_STIM-1];

    int n_fail = 0;

    // Runs the whole stimulus once. `mode` picks the direction per sample:
    // 0 = always down, 1 = always up, 2 = alternate starting with down.
    task automatic run_pass(input int mode, input string name);
        logic                        want_down;
        logic signed [MIX_BITS-1:0]  exp_i, exp_q;
        int                          n_pass_fail;
        begin
            n_pass_fail = 0;

            rst_n = 0;
            in_valid = 0;
            downconvert = 1'b1;
            repeat (2) @(posedge clk);
            rst_n = 1;
            @(posedge clk);

            for (int i = 0; i < N_STIM; i++) begin
                case (mode)
                    0:       want_down = 1'b1;
                    1:       want_down = 1'b0;
                    default: want_down = (i % 2 == 0);
                endcase

                if (want_down) begin
                    exp_i = mix_i_exp[i];
                    exp_q = mix_q_exp[i];
                end else begin
                    exp_i = up_i_exp[i];
                    exp_q = up_q_exp[i];
                end

                xi          = stim_i[i];
                xq          = stim_q[i];
                downconvert = want_down;
                in_valid    = 1;
                @(posedge clk);   // DUT is idle, so this edge always accepts
                in_valid = 0;
                // Drive the direction pin to the *wrong* value while the
                // rotation runs. The operand was captured on the accept edge,
                // so the result must not change; if the mixer read the live
                // pin instead, every sample here would fail.
                downconvert = !want_down;
                while (!out_valid) @(posedge clk);

                if (mix_i !== exp_i || mix_q !== exp_q) begin
                    n_pass_fail++;
                    if (n_pass_fail <= 10) begin
                        $display("FAIL %s sample %0d (%s): xi=%0d xq=%0d",
                                 name, i, want_down ? "down" : "up",
                                 stim_i[i], stim_q[i]);
                        $display("  expected mix_i=%0d mix_q=%0d", exp_i, exp_q);
                        $display("  got      mix_i=%0d mix_q=%0d", mix_i, mix_q);
                    end
                end
                @(posedge clk);
            end

            if (n_pass_fail == 0)
                $display("PASS %-12s %0d samples", name, N_STIM);
            else
                $display("FAIL %-12s %0d of %0d samples", name, n_pass_fail, N_STIM);
            n_fail += n_pass_fail;
        end
    endtask

    initial begin
        $readmemh({VEC_DIR, "/stim_i.hex"},   stim_i);
        $readmemh({VEC_DIR, "/stim_q.hex"},   stim_q);
        $readmemh({VEC_DIR, "/mix_i.hex"},    mix_i_exp);
        $readmemh({VEC_DIR, "/mix_q.hex"},    mix_q_exp);
        $readmemh({VEC_DIR, "/mix_up_i.hex"}, up_i_exp);
        $readmemh({VEC_DIR, "/mix_up_q.hex"}, up_q_exp);

        phase_inc = PHASE_INC;

        run_pass(0, "down");
        run_pass(1, "up");
        run_pass(2, "alternating");

        if (n_fail == 0)
            $display("ALL %0d SAMPLES PASSED", 3 * N_STIM);
        else
            $display("%0d of %0d SAMPLES FAILED", n_fail, 3 * N_STIM);

        $finish;
    end

endmodule
