// Self-checking testbench for ddc_frontend (the fused NCO+mixer datapath),
// in both mixing directions.
//
// Drives build/ddc_vectors (regenerated by rx/run_sim_ddc.sh from
// ddc_reference.py) through the DUT one sample at a time and compares
// mix_i/mix_q against the reference's own fused-mixer output.
//
// Runs three passes -- always down, always up, and alternating per sample --
// since `downconvert` is a runtime port, not a parameter.

`timescale 1ns/1ps
`include "ddc_params.svh"

module tb_ddc_frontend #(
    parameter string VEC_DIR = "build/ddc_vectors"
);

    logic clk = 0;
    logic rst_n;

    logic [PHASE_BITS-1:0]        phase_inc;
    logic                         downconvert;
    logic                         in_valid;
    logic signed [DATA_BITS-1:0]  xi, xq;
    logic                         busy, out_valid;
    logic signed [MIX_BITS-1:0]   mix_i, mix_q;

    ddc_frontend #(
        .PHASE_BITS       (PHASE_BITS),
        .PHASE_TRUNC_BITS (PHASE_TRUNC_BITS),
        .ANG_BITS         (ANG_BITS),
        .DATA_BITS        (DATA_BITS),
        .CORDIC_BITS      (CORDIC_BITS),
        .MIX_BITS         (MIX_BITS)
    ) dut (
        .clk         (clk),
        .rst_n       (rst_n),
        .phase_inc   (phase_inc),
        .downconvert (downconvert),
        .in_valid    (in_valid),
        .xi          (xi),
        .xq          (xq),
        .busy        (busy),
        .out_valid   (out_valid),
        .mix_i       (mix_i),
        .mix_q       (mix_q)
    );

    always #5 clk <= ~clk;

    logic signed [DATA_BITS-1:0] stim_i [0:N_STIM-1];
    logic signed [DATA_BITS-1:0] stim_q [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  mix_i_exp [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  mix_q_exp [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  up_i_exp  [0:N_STIM-1];
    logic signed [MIX_BITS-1:0]  up_q_exp  [0:N_STIM-1];

    int n_fail = 0;

    // Runs the whole stimulus once. `mode` picks the direction per sample:
    // 0 = always down, 1 = always up, 2 = alternate starting with down.
    task automatic run_pass(input int mode, input string name);
        logic                        want_down;
        logic signed [MIX_BITS-1:0]  exp_i, exp_q;
        int                          n_pass_fail;
        begin
            n_pass_fail = 0;

            rst_n = 0;
            in_valid = 0;
            downconvert = 1'b1;
            repeat (2) @(posedge clk);
            rst_n = 1;
            @(posedge clk);

            for (int i = 0; i < N_STIM; i++) begin
                case (mode)
                    0:       want_down = 1'b1;
                    1:       want_down = 1'b0;
                    default: want_down = (i % 2 == 0);
                endcase

                if (want_down) begin
                    exp_i = mix_i_exp[i];
                    exp_q = mix_q_exp[i];
                end else begin
                    exp_i = up_i_exp[i];
                    exp_q = up_q_exp[i];
                end

                xi          = stim_i[i];
                xq          = stim_q[i];
                downconvert = want_down;
                in_valid    = 1;
                @(posedge clk);   // DUT is idle, so this edge always accepts
                in_valid = 0;
                // Drive the direction pin to the *wrong* value while the
                // rotation runs -- the result must not change, since the
                // operand was captured on the accept edge.
                downconvert = !want_down;
                while (!out_valid) @(posedge clk);

                if (mix_i !== exp_i || mix_q !== exp_q) begin
                    n_pass_fail++;
                    if (n_pass_fail <= 10) begin
                        $display("FAIL %s sample %0d (%s): xi=%0d xq=%0d",
                                 name, i, want_down ? "down" : "up",
                                 stim_i[i], stim_q[i]);
                        $display("  expected mix_i=%0d mix_q=%0d", exp_i, exp_q);
                        $display("  got      mix_i=%0d mix_q=%0d", mix_i, mix_q);
                    end
                end
                @(posedge clk);
            end

            if (n_pass_fail == 0)
                $display("PASS %-12s %0d samples", name, N_STIM);
            else
                $display("FAIL %-12s %0d of %0d samples", name, n_pass_fail, N_STIM);
            n_fail += n_pass_fail;
        end
    endtask

    initial begin
        $readmemh({VEC_DIR, "/stim_i.hex"},   stim_i);
        $readmemh({VEC_DIR, "/stim_q.hex"},   stim_q);
        $readmemh({VEC_DIR, "/mix_i.hex"},    mix_i_exp);
        $readmemh({VEC_DIR, "/mix_q.hex"},    mix_q_exp);
        $readmemh({VEC_DIR, "/mix_up_i.hex"}, up_i_exp);
        $readmemh({VEC_DIR, "/mix_up_q.hex"}, up_q_exp);

        phase_inc = PHASE_INC;

        run_pass(0, "down");
        run_pass(1, "up");
        run_pass(2, "alternating");

        if (n_fail == 0)
            $display("ALL %0d SAMPLES PASSED", 3 * N_STIM);
        else begin
            $display("%0d of %0d SAMPLES FAILED", n_fail, 3 * N_STIM);
            $fatal(1, "tb_ddc_frontend: %0d of %0d samples failed", n_fail, 3 * N_STIM);
        end

        $finish;
    end

endmodule
