// Self-checking testbench for fir_decimate.
//
// Drives the same mix_i/mix_q vectors the DDC frontend testbench checks
// (build/ddc_vectors, generated by ddc_reference.py) straight into the FIR,
// and compares against out_i/out_q -- the reference model's own
// fir_decimate() output. Since mix_i/mix_q -> out_i/out_q is exactly
// fir_decimate()'s scope, this checks the FIR in isolation from the mixer
// that normally feeds it.
//
// Run via rx/run_sim_fir.sh, which regenerates the vectors first so the RTL
// and the checked values can never drift apart.

`timescale 1ns/1ps
`include "ddc_params.svh"

module tb_fir_decimate #(
    parameter string VEC_DIR   = "build/ddc_vectors",
    parameter int    SAMPLE_GAP = 19   // clocks between samples; see below
);

    logic clk = 0, rst_n;

    logic                        in_valid;
    logic signed [MIX_BITS-1:0]  xi, xq;
    logic                        out_valid;
    logic signed [OUT_BITS-1:0]  out_i, out_q;

    fir_decimate #(
        .IN_BITS  (MIX_BITS),
        .DECIM    (DECIM),
        .ACC_BITS (ACC_BITS),
        .OUT_BITS (OUT_BITS)
    ) dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .in_valid  (in_valid),
        .xi        (xi),
        .xq        (xq),
        .out_valid (out_valid),
        .out_i     (out_i),
        .out_q     (out_q)
    );

    always #5 clk <= ~clk;

    logic signed [MIX_BITS-1:0] mix_i [0:N_STIM-1];
    logic signed [MIX_BITS-1:0] mix_q [0:N_STIM-1];
    logic signed [OUT_BITS-1:0] out_i_exp [0:N_OUT-1];
    logic signed [OUT_BITS-1:0] out_q_exp [0:N_OUT-1];

    int n_fail = 0;
    int n_out  = 0;

    initial begin
        $readmemh({VEC_DIR, "/mix_i.hex"}, mix_i);
        $readmemh({VEC_DIR, "/mix_q.hex"}, mix_q);
        $readmemh({VEC_DIR, "/out_i.hex"}, out_i_exp);
        $readmemh({VEC_DIR, "/out_q.hex"}, out_q_exp);

        rst_n = 0;
        in_valid = 0;
        repeat (4) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        // Spaced at the mixer's real cadence, not one sample per clock: the
        // MAC engine has no queuing, so a second trigger arriving before the
        // first run finishes (~HALF_TAPS+2 cycles) is a design violation, not
        // something this module is meant to absorb -- it $fatals instead of
        // corrupting the sum. 19 clocks/sample is ddc_frontend's measured
        // throughput (rx/run_throughput.sh), so this also exercises the FIR
        // at the rate it actually has to sustain.
        fork
            begin : producer
                for (int i = 0; i < N_STIM; i++) begin
                    xi = mix_i[i];
                    xq = mix_q[i];
                    in_valid = 1;
                    @(posedge clk);
                    in_valid = 0;
                    repeat (SAMPLE_GAP - 1) @(posedge clk);
                end
            end

            begin : consumer
                while (n_out < N_OUT) begin
                    @(posedge clk);
                    if (out_valid) begin
                        if (out_i !== out_i_exp[n_out] || out_q !== out_q_exp[n_out]) begin
                            n_fail++;
                            if (n_fail <= 10) begin
                                $display("FAIL output %0d", n_out);
                                $display("  expected out_i=%0d out_q=%0d", out_i_exp[n_out], out_q_exp[n_out]);
                                $display("  got      out_i=%0d out_q=%0d", out_i, out_q);
                            end
                        end
                        n_out++;
                    end
                end
            end
        join

        if (n_fail == 0 && n_out == N_OUT)
            $display("ALL %0d OUTPUTS PASSED", N_OUT);
        else
            $display("%0d of %0d OUTPUTS FAILED (%0d produced)", n_fail, N_OUT, n_out);

        $finish;
    end

endmodule
