"""Generates the CORDIC atan table and RTL test vectors from the reference model.

Writes cordic_atan_table.svh next to this script and hex test vectors into an
output directory, so the RTL and its testbench draw the same numbers the
Python reference model produced.

Usage:
    python cordic/gen_cordic_vectors.py --out build/cordic_vectors
"""

import argparse
import json
import os
import sys

import numpy as np

_HERE = os.path.dirname(os.path.abspath(__file__))
_REFERENCE_DIR = os.path.join(_HERE, "reference")
if _REFERENCE_DIR not in sys.path:
    sys.path.insert(0, _REFERENCE_DIR)

import ddc_reference as G

N_ITER = 16
ANG_BITS = 18
WIDTH = 20


def render_atan_table_svh(n_iter, ang_bits):
    """Render the CORDIC atan table as a SystemVerilog include file.

    Args:
        n_iter: Number of CORDIC iterations.
        ang_bits: Angle word width; a full circle is 2**ang_bits.

    Returns:
        The contents of cordic_atan_table.svh as a string.
    """
    table = G.atan_table(n_iter, ang_bits)
    entries = ", ".join(str(int(v)) for v in table)
    return f"""// Generated by cordic/gen_cordic_vectors.py -- do not edit by hand.
// Regenerate:  python cordic/gen_cordic_vectors.py --out build/cordic_vectors
`ifndef CORDIC_ATAN_TABLE_SVH
`define CORDIC_ATAN_TABLE_SVH

`define CORDIC_N_ITER {n_iter}
`define CORDIC_ANG_BITS {ang_bits}

// atan(2^-i) in angle LSBs, i = 0..N_ITER-1. A full circle is 2**ANG_BITS.
// Sized to ANG_BITS, matching the angle path it feeds -- not a generic int,
// so it combines with z_reg without an implicit width change.
localparam logic signed [`CORDIC_ANG_BITS-1:0] CORDIC_ATAN_TABLE [0:`CORDIC_N_ITER-1] = '{{
    {entries}
}};

`endif
"""


def _quadrant_residual_cases(n, quarter, x0, rng, negate):
    """Generate (x0, y0, z0) triples sweeping the quadrant-residual angle range.

    Args:
        n: Number of cases to generate.
        quarter: Quarter-circle bound in angle LSBs; residual z0 is in
            [0, quarter).
        x0: Fixed x seed (the NCO's 1/K-scaled unit vector).
        rng: numpy random Generator.
        negate: If True, negate z0, matching the fused mixer's -rem seeding.

    Returns:
        List of (x0, y0, z0) int triples.
    """
    zs = rng.integers(0, quarter, size=n)
    if negate:
        zs = -zs
    return [(x0, 0, int(z)) for z in zs]


def _signal_rotation_cases(n, quarter, width, rng):
    """Generate (x0, y0, z0) triples simulating the fused mixer rotating a sample.

    Args:
        n: Number of cases to generate.
        quarter: Quarter-circle bound in angle LSBs.
        width: Datapath width for x0, y0.
        rng: numpy random Generator.

    Returns:
        List of (x0, y0, z0) int triples.
    """
    lo, hi = -(1 << (width - 1)), (1 << (width - 1)) - 1
    xs = rng.integers(lo, hi + 1, size=n)
    ys = rng.integers(lo, hi + 1, size=n)
    zs = rng.integers(-quarter, quarter, size=n)
    return list(zip((int(v) for v in xs), (int(v) for v in ys), (int(v) for v in zs)))


def _edge_cases(quarter, width):
    """List the boundary (x0, y0, z0) triples that exercise saturation and range limits.

    Args:
        quarter: Quarter-circle bound in angle LSBs.
        width: Datapath width for x0, y0.

    Returns:
        List of (x0, y0, z0) int triples.
    """
    lo, hi = -(1 << (width - 1)), (1 << (width - 1)) - 1
    vals = [0, hi, lo, hi // 2, lo // 2]
    zs = [0, quarter - 1, -(quarter - 1)]
    return [(x0, y0, z0) for x0 in vals for y0 in vals for z0 in zs]


def build_vectors(n_each=64, seed=0):
    """Build the full CORDIC test vector set.

    Args:
        n_each: Number of random cases per category.
        seed: Seed for the random cases.

    Returns:
        List of (x0, y0, z0) int triples.
    """
    rng = np.random.default_rng(seed)
    quarter = 1 << (ANG_BITS - 2)
    x0_seed = int(round(G.full_scale(WIDTH) / G.cordic_gain(N_ITER)))

    cases = []
    cases += _quadrant_residual_cases(n_each, quarter, x0_seed, rng, negate=False)
    cases += _quadrant_residual_cases(n_each, quarter, x0_seed, rng, negate=True)
    cases += _signal_rotation_cases(n_each, quarter, WIDTH, rng)
    cases += _edge_cases(quarter, WIDTH)
    return cases


def compute_expected(cases):
    """Run the reference model over every case.

    Args:
        cases: List of (x0, y0, z0) int triples.

    Returns:
        List of (x, y, z) int triples, the reference model's output for each case.
    """
    table = G.atan_table(N_ITER, ANG_BITS)
    x0 = np.array([c[0] for c in cases], dtype=np.int64)
    y0 = np.array([c[1] for c in cases], dtype=np.int64)
    z0 = np.array([c[2] for c in cases], dtype=np.int64)
    x, y, z = G.cordic_rotate(x0, y0, z0, table, WIDTH, G.TRUNC)
    return list(zip((int(v) for v in x), (int(v) for v in y), (int(v) for v in z)))


def write_vectors(out_dir, cases, expected):
    """Write stimulus and expected-output hex files plus a manifest.

    Args:
        out_dir: Directory to write into.
        cases: List of (x0, y0, z0) stimulus triples.
        expected: List of (x, y, z) expected output triples.

    Returns:
        The manifest dict that was also written to manifest.json.
    """
    os.makedirs(out_dir, exist_ok=True)
    x0 = np.array([c[0] for c in cases], dtype=np.int64)
    y0 = np.array([c[1] for c in cases], dtype=np.int64)
    z0 = np.array([c[2] for c in cases], dtype=np.int64)
    x = np.array([e[0] for e in expected], dtype=np.int64)
    y = np.array([e[1] for e in expected], dtype=np.int64)
    z = np.array([e[2] for e in expected], dtype=np.int64)

    files = {
        "x_in.hex": (x0, WIDTH),
        "y_in.hex": (y0, WIDTH),
        "z_in.hex": (z0, ANG_BITS),
        "x_out.hex": (x, WIDTH),
        "y_out.hex": (y, WIDTH),
        "z_out.hex": (z, ANG_BITS),
    }
    for name, (arr, bits) in files.items():
        with open(os.path.join(out_dir, name), "w", newline="\n") as f:
            f.write("\n".join(G._hex_lines(arr, bits)) + "\n")

    manifest = {
        "n_iter": N_ITER,
        "ang_bits": ANG_BITS,
        "width": WIDTH,
        "n_vectors": len(cases),
        "files": sorted(files),
    }
    with open(os.path.join(out_dir, "manifest.json"), "w", newline="\n") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")
    return manifest


def main(argv=None):
    """Run the CLI: generate the atan table header and the test vectors.

    Args:
        argv: Argument list to parse; defaults to sys.argv[1:].

    Returns:
        Process exit code.
    """
    p = argparse.ArgumentParser(description="Generate CORDIC RTL vectors from the reference model.")
    p.add_argument("--out", default="build/cordic_vectors", help="output directory for hex vectors")
    p.add_argument("--n-each", type=int, default=64, help="vectors per category")
    p.add_argument("--seed", type=int, default=0, help="random seed")
    a = p.parse_args(argv)

    svh_path = os.path.join(_HERE, "cordic_atan_table.svh")
    with open(svh_path, "w", newline="\n") as f:
        f.write(render_atan_table_svh(N_ITER, ANG_BITS))
    print(f"wrote {svh_path}")

    cases = build_vectors(n_each=a.n_each, seed=a.seed)
    expected = compute_expected(cases)
    manifest = write_vectors(a.out, cases, expected)
    print(f"wrote {manifest['n_vectors']} vectors to {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
