// Self-checking testbench for cordic_core.
//
// Drives every vector in build/cordic_vectors (generated by
// gen_cordic_vectors.py from the reference model) through the DUT one at a
// time and compares against the reference model's own output. Run via
// cordic/run_sim.sh, which regenerates the vectors first so the
// RTL and the checked values can never drift apart.
//
// start is held until busy acknowledges it, so the handshake is correct
// regardless of which state the DUT is in when a new vector begins.

`timescale 1ns/1ps
`include "cordic_atan_table.svh"

module tb_cordic_core #(
    parameter int    NUM_VECTORS = 267,
    parameter string VEC_DIR     = "build/cordic_vectors"
);

    // From the generated header, not restated -- the vectors this testbench
    // reads were produced at exactly this width.
    localparam int WIDTH = `CORDIC_WIDTH;

    logic clk = 0;
    logic rst_n;
    logic start;
    logic signed [WIDTH-1:0]            x_in, y_in;
    logic signed [`CORDIC_ANG_BITS-1:0] z_in;
    logic                               busy, done;
    logic signed [WIDTH-1:0]            x_out, y_out;
    logic signed [`CORDIC_ANG_BITS-1:0] z_out;

    cordic_core #(.WIDTH(WIDTH)) dut (
        .clk    (clk),
        .rst_n  (rst_n),
        .start  (start),
        .x_in   (x_in),
        .y_in   (y_in),
        .z_in   (z_in),
        .busy   (busy),
        .done   (done),
        .x_out  (x_out),
        .y_out  (y_out),
        .z_out  (z_out)
    );

    always #5 clk <= ~clk;

    logic signed [WIDTH-1:0]            x_in_vec  [0:NUM_VECTORS-1];
    logic signed [WIDTH-1:0]            y_in_vec  [0:NUM_VECTORS-1];
    logic signed [`CORDIC_ANG_BITS-1:0] z_in_vec  [0:NUM_VECTORS-1];
    logic signed [WIDTH-1:0]            x_out_exp [0:NUM_VECTORS-1];
    logic signed [WIDTH-1:0]            y_out_exp [0:NUM_VECTORS-1];
    logic signed [`CORDIC_ANG_BITS-1:0] z_out_exp [0:NUM_VECTORS-1];

    int n_fail = 0;

    initial begin
        $readmemh({VEC_DIR, "/x_in.hex"},  x_in_vec);
        $readmemh({VEC_DIR, "/y_in.hex"},  y_in_vec);
        $readmemh({VEC_DIR, "/z_in.hex"},  z_in_vec);
        $readmemh({VEC_DIR, "/x_out.hex"}, x_out_exp);
        $readmemh({VEC_DIR, "/y_out.hex"}, y_out_exp);
        $readmemh({VEC_DIR, "/z_out.hex"}, z_out_exp);

        rst_n = 0;
        start = 0;
        repeat (2) @(posedge clk);
        rst_n = 1;
        @(posedge clk);

        for (int i = 0; i < NUM_VECTORS; i++) begin
            x_in  = x_in_vec[i];
            y_in  = y_in_vec[i];
            z_in  = z_in_vec[i];
            start = 1;
            do @(posedge clk); while (!busy);
            start = 0;
            do @(posedge clk); while (!done);

            if (x_out !== x_out_exp[i] || y_out !== y_out_exp[i] || z_out !== z_out_exp[i]) begin
                n_fail++;
                $display("FAIL vec %0d: x_in=%0d y_in=%0d z_in=%0d", i, x_in_vec[i], y_in_vec[i], z_in_vec[i]);
                $display("  expected x=%0d y=%0d z=%0d", x_out_exp[i], y_out_exp[i], z_out_exp[i]);
                $display("  got      x=%0d y=%0d z=%0d", x_out, y_out, z_out);
            end
        end

        if (n_fail == 0)
            $display("ALL %0d VECTORS PASSED", NUM_VECTORS);
        else begin
            $display("%0d of %0d VECTORS FAILED", n_fail, NUM_VECTORS);
            $fatal(1, "tb_cordic_core: %0d of %0d vectors failed", n_fail, NUM_VECTORS);
        end

        $finish;
    end

endmodule
