// Generated by hardware/cordic/gen_cordic_vectors.py -- do not edit by hand.
// Regenerate:  python hardware/cordic/gen_cordic_vectors.py --out build/cordic_vectors
`ifndef CORDIC_ATAN_TABLE_SVH
`define CORDIC_ATAN_TABLE_SVH

`define CORDIC_N_ITER 16
`define CORDIC_ANG_BITS 18

// atan(2^-i) in angle LSBs, i = 0..N_ITER-1. A full circle is 2**ANG_BITS.
// Sized to ANG_BITS, matching the angle path it feeds -- not a generic int,
// so it combines with z_reg without an implicit width change.
localparam logic signed [`CORDIC_ANG_BITS-1:0] CORDIC_ATAN_TABLE [0:`CORDIC_N_ITER-1] = '{
    32768, 19344, 10221, 5188, 2604, 1303, 652, 326, 163, 81, 41, 20, 10, 5, 3, 1
};

`endif
